In [2]:
from pathlib import Path

import polars as pl

In [4]:
current_directory = Path.cwd()

if current_directory.name == "notebooks":
    project_root = current_directory.parent
else:
    project_root = current_directory

raw_data_directory = project_root / "data" / "raw"

print("Current directory:", current_directory)
print("Project root:", project_root)
print("Raw data directory:", raw_data_directory)

Current directory: /Users/Vihaan/Documents/nfl game predictor/notebooks
Project root: /Users/Vihaan/Documents/nfl game predictor
Raw data directory: /Users/Vihaan/Documents/nfl game predictor/data/raw

In [4]:
for file_path in raw_data_directory.glob("*.parquet"):
    print(file_path.name)

team_stats.parquet
player_stats.parquet
schedules.parquet

In [5]:
schedules = pl.read_parquet(
    raw_data_directory / "schedules.parquet"
)

team_stats = pl.read_parquet(
    raw_data_directory / "team_stats.parquet"
)

player_stats = pl.read_parquet(
    raw_data_directory / "player_stats.parquet"
)

In [6]:
print("Schedules:", schedules.shape)
print("Team stats:", team_stats.shape)
print("Player stats:", player_stats.shape)

Schedules: (2499, 46)
Team stats: (4454, 133)
Player stats: (147223, 145)

In [7]:
schedules.head()

shape: (5, 46)
┌──────────────┬────────┬───────────┬──────┬───┬──────────────┬─────────┬────────────┬─────────────┐
│ game_id      ┆ season ┆ game_type ┆ week ┆ … ┆ home_coach   ┆ referee ┆ stadium_id ┆ stadium     │
│ ---          ┆ ---    ┆ ---       ┆ ---  ┆   ┆ ---          ┆ ---     ┆ ---        ┆ ---         │
│ str          ┆ i32    ┆ str       ┆ i32  ┆   ┆ str          ┆ str     ┆ str        ┆ str         │
╞══════════════╪════════╪═══════════╪══════╪═══╪══════════════╪═════════╪════════════╪═════════════╡
│ 2018_01_ATL_ ┆ 2018   ┆ REG       ┆ 1    ┆ … ┆ Doug         ┆ John    ┆ PHI00      ┆ Lincoln     │
│ PHI          ┆        ┆           ┆      ┆   ┆ Pederson     ┆ Hussey  ┆            ┆ Financial   │
│              ┆        ┆           ┆      ┆   ┆              ┆         ┆            ┆ Field       │
│ 2018_01_BUF_ ┆ 2018   ┆ REG       ┆ 1    ┆ … ┆ John         ┆ Shawn   ┆ BAL00      ┆ M&T Bank    │
│ BAL          ┆        ┆           ┆      ┆   ┆ Harbaugh     ┆ Hochuli ┆            ┆ Stadium     │
│ 2018_01_PIT_ ┆ 2018   ┆ REG       ┆ 1    ┆ … ┆ Hue Jackson  ┆ Shawn   ┆ CLE00      ┆ FirstEnergy │
│ CLE          ┆        ┆           ┆      ┆   ┆              ┆ Smith   ┆            ┆ Stadium     │
│ 2018_01_CIN_ ┆ 2018   ┆ REG       ┆ 1    ┆ … ┆ Frank Reich  ┆ Peter   ┆ IND00      ┆ Lucas Oil   │
│ IND          ┆        ┆           ┆      ┆   ┆              ┆ Morelli ┆            ┆ Stadium     │
│ 2018_01_TEN_ ┆ 2018   ┆ REG       ┆ 1    ┆ … ┆ Adam Gase    ┆ Jerome  ┆ MIA00      ┆ Hard Rock   │
│ MIA          ┆        ┆           ┆      ┆   ┆              ┆ Boger   ┆            ┆ Stadium     │
└──────────────┴────────┴───────────┴──────┴───┴──────────────┴─────────┴────────────┴─────────────┘

In [8]:
team_stats.head()

shape: (5, 133)
┌────────┬──────┬──────┬─────────────┬───┬─────────────┬──────────────┬──────────────┬─────────────┐
│ season ┆ week ┆ team ┆ season_type ┆ … ┆ pt_returned ┆ pt_return_ya ┆ pt_return_td ┆ pt_net_yard │
│ ---    ┆ ---  ┆ ---  ┆ ---         ┆   ┆ ---         ┆ rds          ┆ s            ┆ s           │
│ i32    ┆ i32  ┆ str  ┆ str         ┆   ┆ i32         ┆ ---          ┆ ---          ┆ ---         │
│        ┆      ┆      ┆             ┆   ┆             ┆ i32          ┆ i32          ┆ i32         │
╞════════╪══════╪══════╪═════════════╪═══╪═════════════╪══════════════╪══════════════╪═════════════╡
│ 2018   ┆ 1    ┆ ARI  ┆ REG         ┆ … ┆ 2           ┆ 12           ┆ 0            ┆ 231         │
│ 2018   ┆ 1    ┆ ATL  ┆ REG         ┆ … ┆ 4           ┆ 29           ┆ 0            ┆ 257         │
│ 2018   ┆ 1    ┆ BAL  ┆ REG         ┆ … ┆ 3           ┆ 19           ┆ 0            ┆ 238         │
│ 2018   ┆ 1    ┆ BUF  ┆ REG         ┆ … ┆ 6           ┆ 54           ┆ 0            ┆ 343         │
│ 2018   ┆ 1    ┆ CAR  ┆ REG         ┆ … ┆ 2           ┆ 13           ┆ 0            ┆ 254         │
└────────┴──────┴──────┴─────────────┴───┴─────────────┴──────────────┴──────────────┴─────────────┘

In [9]:
player_stats.head()

shape: (5, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-000409 ┆ P.Dawson  ┆ Phil      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 1         ┆           ┆ Dawson    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001691 ┆ A.Vinatie ┆ Adam      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ ri        ┆ Vinatieri ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001959 ┆ T.Brady   ┆ Tom Brady ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 21.28     ┆ 21.28     │
│ 6         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001964 ┆ S.Janikow ┆ Sebastian ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ ski       ┆ Janikowsk ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ i         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002053 ┆ D.Brees   ┆ Drew      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 31.56     ┆ 31.56     │
│ 1         ┆           ┆ Brees     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
completed_games = schedules.filter(
    pl.col("home_score").is_not_null()
)

upcoming_games = schedules.filter(
    pl.col("home_score").is_null()
)

print("Completed games:", completed_games.height)
print("Upcoming games:", upcoming_games.height)

Completed games: 2227
Upcoming games: 272

In [11]:
upcoming_games.select(
    [
        "season",
        "week",
        "gameday",
        "away_team",
        "home_team",
    ]
).head(20)

shape: (20, 5)
┌────────┬──────┬────────────┬───────────┬───────────┐
│ season ┆ week ┆ gameday    ┆ away_team ┆ home_team │
│ ---    ┆ ---  ┆ ---        ┆ ---       ┆ ---       │
│ i32    ┆ i32  ┆ str        ┆ str       ┆ str       │
╞════════╪══════╪════════════╪═══════════╪═══════════╡
│ 2026   ┆ 1    ┆ 2026-09-09 ┆ NE        ┆ SEA       │
│ 2026   ┆ 1    ┆ 2026-09-10 ┆ SF        ┆ LA        │
│ 2026   ┆ 1    ┆ 2026-09-13 ┆ CHI       ┆ CAR       │
│ 2026   ┆ 1    ┆ 2026-09-13 ┆ TB        ┆ CIN       │
│ 2026   ┆ 1    ┆ 2026-09-13 ┆ NO        ┆ DET       │
│ …      ┆ …    ┆ …          ┆ …         ┆ …         │
│ 2026   ┆ 1    ┆ 2026-09-14 ┆ DEN       ┆ KC        │
│ 2026   ┆ 2    ┆ 2026-09-17 ┆ DET       ┆ BUF       │
│ 2026   ┆ 2    ┆ 2026-09-20 ┆ CAR       ┆ ATL       │
│ 2026   ┆ 2    ┆ 2026-09-20 ┆ NO        ┆ BAL       │
│ 2026   ┆ 2    ┆ 2026-09-20 ┆ MIN       ┆ CHI       │
└────────┴──────┴────────────┴───────────┴───────────┘

In [12]:
completed_games = schedules.filter(
    pl.col("home_score").is_not_null()
    & pl.col("away_score").is_not_null()
)

completed_games.select(
    [
        "season",
        "week",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
    ]
).head()

shape: (5, 6)
┌────────┬──────┬───────────┬───────────┬────────────┬────────────┐
│ season ┆ week ┆ home_team ┆ away_team ┆ home_score ┆ away_score │
│ ---    ┆ ---  ┆ ---       ┆ ---       ┆ ---        ┆ ---        │
│ i32    ┆ i32  ┆ str       ┆ str       ┆ i32        ┆ i32        │
╞════════╪══════╪═══════════╪═══════════╪════════════╪════════════╡
│ 2018   ┆ 1    ┆ PHI       ┆ ATL       ┆ 18         ┆ 12         │
│ 2018   ┆ 1    ┆ BAL       ┆ BUF       ┆ 47         ┆ 3          │
│ 2018   ┆ 1    ┆ CLE       ┆ PIT       ┆ 21         ┆ 21         │
│ 2018   ┆ 1    ┆ IND       ┆ CIN       ┆ 23         ┆ 34         │
│ 2018   ┆ 1    ┆ MIA       ┆ TEN       ┆ 27         ┆ 20         │
└────────┴──────┴───────────┴───────────┴────────────┴────────────┘

In [13]:
completed_games = completed_games.with_columns(
    (pl.col("home_score") > pl.col("away_score"))
    .cast(pl.Int8)
    .alias("home_win")
)

In [14]:
completed_games.select(
    [
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "home_win",
    ]
).head(10)

shape: (10, 5)
┌───────────┬───────────┬────────────┬────────────┬──────────┐
│ home_team ┆ away_team ┆ home_score ┆ away_score ┆ home_win │
│ ---       ┆ ---       ┆ ---        ┆ ---        ┆ ---      │
│ str       ┆ str       ┆ i32        ┆ i32        ┆ i8       │
╞═══════════╪═══════════╪════════════╪════════════╪══════════╡
│ PHI       ┆ ATL       ┆ 18         ┆ 12         ┆ 1        │
│ BAL       ┆ BUF       ┆ 47         ┆ 3          ┆ 1        │
│ CLE       ┆ PIT       ┆ 21         ┆ 21         ┆ 0        │
│ IND       ┆ CIN       ┆ 23         ┆ 34         ┆ 0        │
│ MIA       ┆ TEN       ┆ 27         ┆ 20         ┆ 1        │
│ MIN       ┆ SF        ┆ 24         ┆ 16         ┆ 1        │
│ NE        ┆ HOU       ┆ 27         ┆ 20         ┆ 1        │
│ NO        ┆ TB        ┆ 40         ┆ 48         ┆ 0        │
│ NYG       ┆ JAX       ┆ 15         ┆ 20         ┆ 0        │
│ LAC       ┆ KC        ┆ 28         ┆ 38         ┆ 0        │
└───────────┴───────────┴────────────┴────────────┴──────────┘

In [15]:
completed_games = completed_games.filter(
    pl.col("home_score") != pl.col("away_score")
)

In [16]:
print(team_stats.columns)

['season', 'week', 'team', 'season_type', 'game_id', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'timeouts', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards']

In [5]:
model_data = pl.read_parquet(
    raw_data_directory.parent
    / "processed"
    / "model_data.parquet"
)

model_data.shape

(1964, 17)

In [6]:
model_data.head()

shape: (5, 17)
┌─────────────┬────────┬──────┬────────────┬───┬─────────────┬────────────┬────────────┬───────────┐
│ game_id     ┆ season ┆ week ┆ gameday    ┆ … ┆ recent_sack ┆ recent_def ┆ recent_def ┆ rest_diff │
│ ---         ┆ ---    ┆ ---  ┆ ---        ┆   ┆ s_suffered_ ┆ _sacks_dif ┆ _intercept ┆ ---       │
│ str         ┆ i32    ┆ i32  ┆ str        ┆   ┆ diff        ┆ f          ┆ ions_diff  ┆ i32       │
│             ┆        ┆      ┆            ┆   ┆ ---         ┆ ---        ┆ ---        ┆           │
│             ┆        ┆      ┆            ┆   ┆ f64         ┆ f64        ┆ f64        ┆           │
╞═════════════╪════════╪══════╪════════════╪═══╪═════════════╪════════════╪════════════╪═══════════╡
│ 2018_02_ARI ┆ 2018   ┆ 2    ┆ 2018-09-16 ┆ … ┆ -1.0        ┆ -2.0       ┆ 3.0        ┆ -1        │
│ _LA         ┆        ┆      ┆            ┆   ┆             ┆            ┆            ┆           │
│ 2018_02_BAL ┆ 2018   ┆ 2    ┆ 2018-09-13 ┆ … ┆ 0.0         ┆ -4.0       ┆ -1.0       ┆ 0         │
│ _CIN        ┆        ┆      ┆            ┆   ┆             ┆            ┆            ┆           │
│ 2018_02_CAR ┆ 2018   ┆ 2    ┆ 2018-09-16 ┆ … ┆ 1.0         ┆ -4.0       ┆ 1.0        ┆ 3         │
│ _ATL        ┆        ┆      ┆            ┆   ┆             ┆            ┆            ┆           │
│ 2018_02_CLE ┆ 2018   ┆ 2    ┆ 2018-09-16 ┆ … ┆ -6.0        ┆ -4.0       ┆ -3.0       ┆ 0         │
│ _NO         ┆        ┆      ┆            ┆   ┆             ┆            ┆            ┆           │
│ 2018_02_DET ┆ 2018   ┆ 2    ┆ 2018-09-16 ┆ … ┆ 3.0         ┆ 1.0        ┆ -1.0       ┆ 1         │
│ _SF         ┆        ┆      ┆            ┆   ┆             ┆            ┆            ┆           │
└─────────────┴────────┴──────┴────────────┴───┴─────────────┴────────────┴────────────┴───────────┘

In [7]:
model_data.group_by("home_win").len()

shape: (2, 2)
┌──────────┬──────┐
│ home_win ┆ len  │
│ ---      ┆ ---  │
│ i8       ┆ u64  │
╞══════════╪══════╡
│ 1        ┆ 1061 │
│ 0        ┆ 903  │
└──────────┴──────┘

In [8]:
model_data.null_count()

shape: (1, 17)
┌─────────┬────────┬──────┬─────────┬───┬───────────────┬───────────────┬──────────────┬───────────┐
│ game_id ┆ season ┆ week ┆ gameday ┆ … ┆ recent_sacks_ ┆ recent_def_sa ┆ recent_def_i ┆ rest_diff │
│ ---     ┆ ---    ┆ ---  ┆ ---     ┆   ┆ suffered_diff ┆ cks_diff      ┆ nterceptions ┆ ---       │
│ u64     ┆ u64    ┆ u64  ┆ u64     ┆   ┆ ---           ┆ ---           ┆ _diff        ┆ u64       │
│         ┆        ┆      ┆         ┆   ┆ u64           ┆ u64           ┆ ---          ┆           │
│         ┆        ┆      ┆         ┆   ┆               ┆               ┆ u64          ┆           │
╞═════════╪════════╪══════╪═════════╪═══╪═══════════════╪═══════════════╪══════════════╪═══════════╡
│ 0       ┆ 0      ┆ 0    ┆ 0       ┆ … ┆ 0             ┆ 0             ┆ 0            ┆ 0         │
└─────────┴────────┴──────┴─────────┴───┴───────────────┴───────────────┴──────────────┴───────────┘